// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package start

import (
	"github.com/bwmarrin/discordgo"
	"github.com/imle/discord-bot-event-channels/pkg/bot"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

func InitializeEventManager(logger *logrus.Logger, engineConfig EngineConfig) (*bot.EventManager, error) {
	engineInterface, err := NewEngine(engineConfig)
	if err != nil {
		return nil, err
	}
	eventManager := bot.NewEventManager(logger, engineInterface)
	return eventManager, nil
}

func InitializeDiscordGoSession(logger *logrus.Logger, discordSessionConfig DiscordSessionConfig) (*discordgo.Session, error) {
	session, err := NewDiscordGoSession(discordSessionConfig)
	if err != nil {
		return nil, err
	}
	return session, nil
}
